// import React from "react";

const data = [
    {
        workPermitNo: '12345',
        status: 'red',
        area: 'Building 5',
        subArea: 'First Floor Ceiling area',
        permitType: 'Hot Height',
        startDate: '07/27/23',
        endDate: '08/27/23',
        requiringDepartment: 'CVL-R',
        issuingDepartment: 'EN7F',
        kyStatus: 'Updated',
        riskCategory: 'High',

        checkSheetStatus: 'Updated', activeKySheets: [
            {
                "kySheetNo": 12345,
                "date": "07/27/23",
                "area": "Building 5",
                "subArea": "First Floor Ceiling area",
                "requiringDepartment": "CVL-R",
                "issuingDepartment": "EN7F",
            },
            {
                "kySheetNo": 77889,
                "date": "07/28/23",
                "area": "Building 51",
                "subArea": "First Floor Ceiling area",
                "requiringDepartment": "CVL-R",
                "issuingDepartment": "ENZF",
            },
            {
                "kySheetNo": 22345,
                "date": "07/29/23",
                "area": "Building 6",
                "subArea": "Second Floor Ceiling area",
                "requiringDepartment": "CVL-S",
                "issuingDepartment": "EN8F",
            },
            {
                "kySheetNo": 98745,
                "date": "07/30/23",
                "area": "Building 52",
                "subArea": "Second Floor Ceiling area",
                "requiringDepartment": "CVL-T",
                "issuingDepartment": "EN7G",
            },
            {
                "kySheetNo": 76547,
                "date": "07/31/23",
                "area": "Building 7",
                "subArea": "Third Floor Ceiling area",
                "requiringDepartment": "CVL-U",
                "issuingDepartment": "EN7H",
            },
            {
                "kySheetNo": 12350,
                "date": "08/01/23",
                "area": "Building 53",
                "subArea": "Third Floor Ceiling area",
                "requiringDepartment": "CVL-V",
                "issuingDepartment": "EN7I",
            },


        ],
        activeCheckList: [
            {
                kySheetNo: 12745,
                date: "07/27/23",
                area: "Builing 5",
                subArea: "First Floor Ceiling area",
                requiringDepartment: "CVL-R",
                issuingDepartment: "EN7F",
            },
            {
                kySheetNo: 12346,
                date: "07/28/23",
                area: "Builing 51",
                subArea: "First Floor Ceiling area",
                requiringDepartment: "CVL-R",
                issuingDepartment: "ENZF",
            },
        ],
    },
    {
        workPermitNo: '67890',
        status: 'green',
        area: 'Building 5',
        subArea: 'First Floor Ceiling area',
        permitType: 'Hot Height',
        startDate: '07/27/23',
        endDate: '08/27/23',
        requiringDepartment: 'CVL-R',
        issuingDepartment: 'EN7F',
        kyStatus: 'Updated',
        riskCategory: 'High',

        checkSheetStatus: 'Updated', activeKySheets: [
            {
                "kySheetNo": 12345,
                "date": "07/27/23",
                "area": "Building 5",
                "subArea": "First Floor Ceiling area",
                "requiringDepartment": "CVL-R",
                "issuingDepartment": "EN7F",
            },
            {
                "kySheetNo": 77889,
                "date": "07/28/23",
                "area": "Building 51",
                "subArea": "First Floor Ceiling area",
                "requiringDepartment": "CVL-R",
                "issuingDepartment": "ENZF",
            },
            {
                "kySheetNo": 22345,
                "date": "07/29/23",
                "area": "Building 6",
                "subArea": "Second Floor Ceiling area",
                "requiringDepartment": "CVL-S",
                "issuingDepartment": "EN8F",
            },
            {
                "kySheetNo": 98745,
                "date": "07/30/23",
                "area": "Building 52",
                "subArea": "Second Floor Ceiling area",
                "requiringDepartment": "CVL-T",
                "issuingDepartment": "EN7G",
            },
            {
                "kySheetNo": 76547,
                "date": "07/31/23",
                "area": "Building 7",
                "subArea": "Third Floor Ceiling area",
                "requiringDepartment": "CVL-U",
                "issuingDepartment": "EN7H",
            },
            {
                "kySheetNo": 12350,
                "date": "08/01/23",
                "area": "Building 53",
                "subArea": "Third Floor Ceiling area",
                "requiringDepartment": "CVL-V",
                "issuingDepartment": "EN7I",
            },


        ],
        activeCheckList: [
            {
                kySheetNo: 12745,
                date: "07/27/23",
                area: "Builing 5",
                subArea: "First Floor Ceiling area",
                requiringDepartment: "CVL-R",
                issuingDepartment: "EN7F",
            },
            {
                kySheetNo: 12346,
                date: "07/28/23",
                area: "Builing 51",
                subArea: "First Floor Ceiling area",
                requiringDepartment: "CVL-R",
                issuingDepartment: "ENZF",
            },
        ],
    },
    {
        workPermitNo: '54321',
        status: 'yellow',
        area: 'Building 6',
        subArea: 'Second Floor Roof area',
        permitType: 'Cold Height',
        startDate: '07/28/23',
        endDate: '08/28/23',
        requiringDepartment: 'ELE-R',
        issuingDepartment: 'EN6F',
        kyStatus: 'Pending',
        riskCategory: 'Medium',
        checkSheetStatus: 'Updated', activeKySheets: [
            {
                "kySheetNo": 12345,
                "date": "07/27/23",
                "area": "Building 5",
                "subArea": "First Floor Ceiling area",
                "requiringDepartment": "CVL-R",
                "issuingDepartment": "EN7F",
            },
            {
                "kySheetNo": 77889,
                "date": "07/28/23",
                "area": "Building 51",
                "subArea": "First Floor Ceiling area",
                "requiringDepartment": "CVL-R",
                "issuingDepartment": "ENZF",
            },
            {
                "kySheetNo": 22345,
                "date": "07/29/23",
                "area": "Building 6",
                "subArea": "Second Floor Ceiling area",
                "requiringDepartment": "CVL-S",
                "issuingDepartment": "EN8F",
            },
            {
                "kySheetNo": 98745,
                "date": "07/30/23",
                "area": "Building 52",
                "subArea": "Second Floor Ceiling area",
                "requiringDepartment": "CVL-T",
                "issuingDepartment": "EN7G",
            },
            {
                "kySheetNo": 76547,
                "date": "07/31/23",
                "area": "Building 7",
                "subArea": "Third Floor Ceiling area",
                "requiringDepartment": "CVL-U",
                "issuingDepartment": "EN7H",
            },
            {
                "kySheetNo": 12350,
                "date": "08/01/23",
                "area": "Building 53",
                "subArea": "Third Floor Ceiling area",
                "requiringDepartment": "CVL-V",
                "issuingDepartment": "EN7I",
            },


        ],
        activeCheckList: [
            {
                kySheetNo: 12745,
                date: "07/27/23",
                area: "Builing 5",
                subArea: "First Floor Ceiling area",
                requiringDepartment: "CVL-R",
                issuingDepartment: "EN7F",
            },
            {
                kySheetNo: 12346,
                date: "07/28/23",
                area: "Builing 51",
                subArea: "First Floor Ceiling area",
                requiringDepartment: "CVL-R",
                issuingDepartment: "ENZF",
            },
        ],
    },
    {
        workPermitNo: '98765',
        status: 'green',
        area: 'Building 7',
        subArea: 'Third Floor Electrical area',
        permitType: 'Hot Height',
        startDate: '07/29/23',
        endDate: '08/29/23',
        requiringDepartment: 'ELE-R',
        issuingDepartment: 'EN7F',
        kyStatus: 'Updated',
        riskCategory: 'High',
        checkSheetStatus: 'Updated', activeKySheets: [
            {
                "kySheetNo": 12345,
                "date": "07/27/23",
                "area": "Building 5",
                "subArea": "First Floor Ceiling area",
                "requiringDepartment": "CVL-R",
                "issuingDepartment": "EN7F",
            },
            {
                "kySheetNo": 77889,
                "date": "07/28/23",
                "area": "Building 51",
                "subArea": "First Floor Ceiling area",
                "requiringDepartment": "CVL-R",
                "issuingDepartment": "ENZF",
            },
            {
                "kySheetNo": 22345,
                "date": "07/29/23",
                "area": "Building 6",
                "subArea": "Second Floor Ceiling area",
                "requiringDepartment": "CVL-S",
                "issuingDepartment": "EN8F",
            },
            {
                "kySheetNo": 98745,
                "date": "07/30/23",
                "area": "Building 52",
                "subArea": "Second Floor Ceiling area",
                "requiringDepartment": "CVL-T",
                "issuingDepartment": "EN7G",
            },
            {
                "kySheetNo": 76547,
                "date": "07/31/23",
                "area": "Building 7",
                "subArea": "Third Floor Ceiling area",
                "requiringDepartment": "CVL-U",
                "issuingDepartment": "EN7H",
            },
            {
                "kySheetNo": 12350,
                "date": "08/01/23",
                "area": "Building 53",
                "subArea": "Third Floor Ceiling area",
                "requiringDepartment": "CVL-V",
                "issuingDepartment": "EN7I",
            },


        ],
        activeCheckList: [
            {
                kySheetNo: 12745,
                date: "07/27/23",
                area: "Builing 5",
                subArea: "First Floor Ceiling area",
                requiringDepartment: "CVL-R",
                issuingDepartment: "EN7F",
            },
            {
                kySheetNo: 12346,
                date: "07/28/23",
                area: "Builing 51",
                subArea: "First Floor Ceiling area",
                requiringDepartment: "CVL-R",
                issuingDepartment: "ENZF",
            },
        ],
    },
    {
        workPermitNo: '24680',
        status: 'red',
        area: 'Building 8',
        subArea: 'Fourth Floor Plumbing area',
        permitType: 'Cold Height',
        startDate: '07/30/23',
        endDate: '08/30/23',
        requiringDepartment: 'PLM-R',
        issuingDepartment: 'EN8F',
        kyStatus: 'Updated',
        riskCategory: 'High',
        checkSheetStatus: 'Updated', activeKySheets: [
            {
                "kySheetNo": 12345,
                "date": "07/27/23",
                "area": "Building 5",
                "subArea": "First Floor Ceiling area",
                "requiringDepartment": "CVL-R",
                "issuingDepartment": "EN7F",
            },
            {
                "kySheetNo": 77889,
                "date": "07/28/23",
                "area": "Building 51",
                "subArea": "First Floor Ceiling area",
                "requiringDepartment": "CVL-R",
                "issuingDepartment": "ENZF",
            },
            {
                "kySheetNo": 22345,
                "date": "07/29/23",
                "area": "Building 6",
                "subArea": "Second Floor Ceiling area",
                "requiringDepartment": "CVL-S",
                "issuingDepartment": "EN8F",
            },
            {
                "kySheetNo": 98745,
                "date": "07/30/23",
                "area": "Building 52",
                "subArea": "Second Floor Ceiling area",
                "requiringDepartment": "CVL-T",
                "issuingDepartment": "EN7G",
            },
            {
                "kySheetNo": 76547,
                "date": "07/31/23",
                "area": "Building 7",
                "subArea": "Third Floor Ceiling area",
                "requiringDepartment": "CVL-U",
                "issuingDepartment": "EN7H",
            },
            {
                "kySheetNo": 12350,
                "date": "08/01/23",
                "area": "Building 53",
                "subArea": "Third Floor Ceiling area",
                "requiringDepartment": "CVL-V",
                "issuingDepartment": "EN7I",
            },


        ],
        activeCheckList: [
            {
                kySheetNo: 12745,
                date: "07/27/23",
                area: "Builing 5",
                subArea: "First Floor Ceiling area",
                requiringDepartment: "CVL-R",
                issuingDepartment: "EN7F",
            },
            {
                kySheetNo: 12346,
                date: "07/28/23",
                area: "Builing 51",
                subArea: "First Floor Ceiling area",
                requiringDepartment: "CVL-R",
                issuingDepartment: "ENZF",
            },
        ],
    },
    {
        workPermitNo: '13579',
        status: 'green',
        area: 'Building 9',
        subArea: 'Fifth Floor Ventilation area',
        permitType: 'Hot Height',
        startDate: '07/31/23',
        endDate: '08/31/23',
        requiringDepartment: 'VENT-R',
        issuingDepartment: 'EN9F',
        kyStatus: 'Updated',
        riskCategory: 'High',
        checkSheetStatus: 'Updated', activeKySheets: [
            {
                "kySheetNo": 12345,
                "date": "07/27/23",
                "area": "Building 5",
                "subArea": "First Floor Ceiling area",
                "requiringDepartment": "CVL-R",
                "issuingDepartment": "EN7F",
            },
            {
                "kySheetNo": 77889,
                "date": "07/28/23",
                "area": "Building 51",
                "subArea": "First Floor Ceiling area",
                "requiringDepartment": "CVL-R",
                "issuingDepartment": "ENZF",
            },
            {
                "kySheetNo": 22345,
                "date": "07/29/23",
                "area": "Building 6",
                "subArea": "Second Floor Ceiling area",
                "requiringDepartment": "CVL-S",
                "issuingDepartment": "EN8F",
            },
            {
                "kySheetNo": 98745,
                "date": "07/30/23",
                "area": "Building 52",
                "subArea": "Second Floor Ceiling area",
                "requiringDepartment": "CVL-T",
                "issuingDepartment": "EN7G",
            },
            {
                "kySheetNo": 76547,
                "date": "07/31/23",
                "area": "Building 7",
                "subArea": "Third Floor Ceiling area",
                "requiringDepartment": "CVL-U",
                "issuingDepartment": "EN7H",
            },
            {
                "kySheetNo": 12350,
                "date": "08/01/23",
                "area": "Building 53",
                "subArea": "Third Floor Ceiling area",
                "requiringDepartment": "CVL-V",
                "issuingDepartment": "EN7I",
            },


        ],
        activeCheckList: [
            {
                kySheetNo: 12745,
                date: "07/27/23",
                area: "Builing 5",
                subArea: "First Floor Ceiling area",
                requiringDepartment: "CVL-R",
                issuingDepartment: "EN7F",
            },
            {
                kySheetNo: 12346,
                date: "07/28/23",
                area: "Builing 51",
                subArea: "First Floor Ceiling area",
                requiringDepartment: "CVL-R",
                issuingDepartment: "ENZF",
            },
        ],
    },
    {
        workPermitNo: '11223',
        status: 'red',
        area: 'Building 10',
        subArea: 'Sixth Floor Maintenance area',
        permitType: 'Cold Height',
        startDate: '08/01/23',
        endDate: '09/01/23',
        requiringDepartment: 'MNT-R',
        issuingDepartment: 'EN10F',
        kyStatus: 'Updated',
        riskCategory: 'High',
        checkSheetStatus: 'Updated', activeKySheets: [
            {
                "kySheetNo": 12345,
                "date": "07/27/23",
                "area": "Building 5",
                "subArea": "First Floor Ceiling area",
                "requiringDepartment": "CVL-R",
                "issuingDepartment": "EN7F",
            },
            {
                "kySheetNo": 77889,
                "date": "07/28/23",
                "area": "Building 51",
                "subArea": "First Floor Ceiling area",
                "requiringDepartment": "CVL-R",
                "issuingDepartment": "ENZF",
            },
            {
                "kySheetNo": 22345,
                "date": "07/29/23",
                "area": "Building 6",
                "subArea": "Second Floor Ceiling area",
                "requiringDepartment": "CVL-S",
                "issuingDepartment": "EN8F",
            },
            {
                "kySheetNo": 98745,
                "date": "07/30/23",
                "area": "Building 52",
                "subArea": "Second Floor Ceiling area",
                "requiringDepartment": "CVL-T",
                "issuingDepartment": "EN7G",
            },
            {
                "kySheetNo": 76547,
                "date": "07/31/23",
                "area": "Building 7",
                "subArea": "Third Floor Ceiling area",
                "requiringDepartment": "CVL-U",
                "issuingDepartment": "EN7H",
            },
            {
                "kySheetNo": 12350,
                "date": "08/01/23",
                "area": "Building 53",
                "subArea": "Third Floor Ceiling area",
                "requiringDepartment": "CVL-V",
                "issuingDepartment": "EN7I",
            },


        ],
        activeCheckList: [
            {
                kySheetNo: 12745,
                date: "07/27/23",
                area: "Builing 5",
                subArea: "First Floor Ceiling area",
                requiringDepartment: "CVL-R",
                issuingDepartment: "EN7F",
            },
            {
                kySheetNo: 12346,
                date: "07/28/23",
                area: "Builing 51",
                subArea: "First Floor Ceiling area",
                requiringDepartment: "CVL-R",
                issuingDepartment: "ENZF",
            },
        ],
    },
];

export const getData = (workPermitNo) => {
    if (!workPermitNo) return data;
    console.log(workPermitNo, data.find(el => el.workPermitNo == workPermitNo));
    return data.find(el => el.workPermitNo == workPermitNo);
}

export default getData;